xnvme/xnvme

- tools/fio-engine/xnvme_fioe.c
Signed-off-by: Pierre Labat <plabat@micron.com>
The problem is exposed when running fio random write on a zns device via xnvme.
Fio, after a while, fills up a number of zones. Then it starts to reset some zones, one at a time.
When fio reset a zone xnvme_fioe_reset_wp() is called. 
xnvme_fioe_reset_wp() resets 2 zones instead of only one as it should. The next one is also reset.
Later, when fio tries to write in the zone reset by mistake (and without fio being aware of it), the zns device returns a write error because fio thinks the WP is A  (with A > zone start) while on the device it the WP is now zone start. The FIO tests fails.
I tested the fix, and with it, the fio test completes without error.
> xnvme_fioe_reset_wp() was resetting one too many zone

- Makefile
- scripts/print_help.py
- Created a python script to go through the Makefile and pick up on macros defined as `*-help`
- Converted existing documentation into the new format
> Add 'make help' target to document the Makefile

- lib/meson.build
meson: only do whole-archive in pkg-config when SPDK is enabled
The generated pkg-config produces linker-args for whole-archive-linking.
This is needed by the __attribute__((destructor)) used by SPDK to load
modules. E.g. the SPDK NVMe driver is registered via such as
constructor.
In some environments/toolchains this is causing issues, those same
environments do not support SPDK. Thus, this change restricts the
addition of these flags to when the xNVMe SPDK backend is enabled.
> meson: only do whole-archive in pkg-config when SPDK is enabled

- lib/xnvme_be_linux_async_libaio.c
- lib/xnvme_be_linux_async_liburing.c
- lib/xnvme_be_linux_async_ucmd.c
- lib/xnvme_be_posix_async_aio.c
- lib/xnvme_be_posix_async_emu.c
- lib/xnvme_be_posix_async_nil.c
- lib/xnvme_be_posix_async_thrpool.c
- lib/xnvme_be_spdk_async.c
- lib/xnvme_be_windows_async_iocp.c
- lib/xnvme_be_windows_async_iocp_th.c
- lib/xnvme_cmd.c
be,cmd: hoist the queue-busy-guard from backends into 'xnvme_cmd'
On the submission-path in every async-backend implementation a 'BUSY'
guard ensures that the backend-implementation would not proceed but
instead exit early and return '-EBUSY'.
Since all the engines do this, then it can conveniently be handled by
the 'xnvme_cmd'-module instead, upon async-submission. This change does
so.
> be,cmd: Hoist the queue-busy-guard from backends into 'xnvme_cmd'

- Makefile
- scripts/pkgs/opensuse-tumbleweed-latest.sh
The Makefile-helper 'make git-setup' is invoked via the default
make-target thereby providing an implicit setup of git-hooks and
git-blame-ignore-files. Which is convenient. However, the build using
Makefile might be building from source-archive instead. Thus, this fix
to ignore the git-setup error.
> mk: fix 'git-setup' error when using src-archive

- docs/autogen/doxy.cfg
- include libxnvme_libconf instead of libxnvme_3p
- include libxnvme_spec_fs instead of libxnvme_spec_file
> Docs: fix doxygen includes

- examples/xnvme_io_async.c
- include/xnvme_be_linux_nvme.h
- lib/xnvme_be_linux_async_ucmd.c
- lib/xnvme_be_linux_nvme.c
- lib/xnvme_be_posix_async_emu.c
- lib/xnvme_be_posix_async_thrpool.c
- lib/xnvme_libconf.c
- scripts/cijoe-pkg-xnvme/testplans/xnvme-nvm-linux-ucmd.plan
This is related to:
- Issue: https://github.com/OpenMPDK/xNVMe/issues/50
- PR: https://github.com/OpenMPDK/xNVMe/pull/43
- PR: https://github.com/OpenMPDK/xNVMe/pull/49
The PR does not address the ``big-sqe``, also the sync. NVMe-ioctl-iovec, definately needs another set of eyes.
> Refreshing ``io_uring_cmd`` backend

- .github/workflows/verify.yml
Although GitHUB is unaffected by the CVEs then the workflow generating the source-archive for xNVMe broke.
The change on this PR fixes it.
> This fixed CI issues indirectly introduced by CVE-2022-24765 and CVE-2022-24767

- include/libxnvme_adm.h
- include/libxnvme_be.h
- include/libxnvme_buf.h
- include/libxnvme_dev.h
- include/libxnvme_lba.h
- include/libxnvme_pp.h
- include/libxnvme_sgl.h
- include/libxnvme_ver.h
- lib/meson.build
- lib/xnvme_be.c
- lib/xnvme_ident.c
- lib/xnvme_opts.c
Changes done in preparation for Python language bindings.
The main thing is the addition of ``xnvme_opts_pr()`` as it is used to check the Python bindings.
That is, that the visually inspect that the misc assignments of **const char pointer**, bitfields and numerical values carry over correctly from Python to C.
> Misc. fixes and preps for Python language bindings

- .github/workflows/verify.yml
- subprojects/packagefiles/liburing/liburing_patches.sh
- subprojects/packagefiles/liburing/meson.build
In order to enable the big-sqe/big-cqe/uring_cmd the the subproject needs an update.
An issue was discovered with Alpine Linux and the availability of STATX via ``sys/stat.h``.
This is an attempt at working around it, invoking the build-ci to see how it behaves.
> Exploring muslc issue with liburing master (+uring_cmd)

- include/xnvme_be_linux_liburing.h
- lib/xnvme_be_linux_async_liburing.c
- lib/xnvme_be_linux_async_ucmd.c
- lib/xnvme_be_linux_nvme.c
- subprojects/liburing.wrap
_Supports Regular & Vectored I/O with 128 byte SQEs and 32 byte CQEs_
**Sample Commands :**
**Regular I/O :**
_fio ./tools/fio-engine/xnvme-verify.fio --section=default --ioengine=external:./builddir/tools/fio-engine/libxnvme-fio-engine.so --filename=/dev/ng0n1 --xnvme_async=io_uring_cmd_
**Vectored I/O :**
_fio ./tools/fio-engine/xnvme-verify.fio --section=default --ioengine=external:./builddir/tools/fio-engine/libxnvme-fio-engine.so --filename=/dev/ng0n1 --xnvme_async=io_uring_cmd --xnvme_iovec=1_
> be:linux:ucmd: add Support for Big-SQE / Big-CQEs

- lib/xnvme_be_ramdisk_dev.c
Broke the build when debug was enabled. This fixes it.
> be:ramdisk: fix debug-message

- .github/workflows/verify.yml
- .pre-commit-config.yaml
- docs/index.rst
- docs/python/index.rst
- python/.gitignore
- python/LICENSE
- python/Makefile
- python/README.rst
- python/aux/patch_ctypes_mapping.py
- python/bin/xpy_dev_open
- python/bin/xpy_enumerate
- python/bin/xpy_libconf
- python/pyproject.toml
- python/requirements.txt
- python/setup.py
- python/xnvme/library_loader.py
- python/xnvme/tests/test_loader.py
- toolbox/cijoe-pkg-xnvme/testcases/xpy_dev_open.sh
- toolbox/cijoe-pkg-xnvme/testcases/xpy_enumerate.sh
- toolbox/cijoe-pkg-xnvme/testcases/xpy_libconf.sh
- toolbox/cijoe-pkg-xnvme/testplans/xnvme-python.plan
xNVMe previously had Python bindings, however, these where manually written wrappers which were not properly tested, thus they became stale and were removed from the repository.
However, recently when providing examples of how to dynamically load xNVMe from C and Python, then it seemed worth-while to explore just how much is possible via ``ctypes``. With a couple of non-intrusive changes to the public C API (adding a couple of includes), then it is possible to auto-generate a complete ctypes-wrapping for the C API. With the essentials auto-generated, then using ``ctypes`` is a breeze.
With this PR a full xNVMe C API mapping is available along with automatic dynamic loading. This module can serve for those wanting to experiment with the API from the comforts of Python. Additionally, as a …
> Revive the xNVMe Python language bindings

- .github/workflows/verify.yml
- include/xnvme_be_registry.h
- include/xnvme_be_vfio.h
- lib/meson.build
- lib/xnvme_be.c
- lib/xnvme_be_vfio.c
- lib/xnvme_be_vfio_admin.c
- lib/xnvme_be_vfio_async.c
- lib/xnvme_be_vfio_dev.c
- lib/xnvme_be_vfio_mem.c
- lib/xnvme_be_vfio_sync.c
- meson.build
- meson_options.txt
- subprojects/libvfn.wrap
- toolbox/cijoe-pkg-xnvme/envs/refenv-xnvme-qemu.sh
- toolbox/cijoe-pkg-xnvme/envs/refenv-xnvme.sh
- toolbox/cijoe-pkg-xnvme/hooks/xnvme_enter.sh
- toolbox/cijoe-pkg-xnvme/testplans/README.rst
- toolbox/cijoe-pkg-xnvme/testplans/xnvme-base-vfio.plan
- toolbox/cijoe-pkg-xnvme/testplans/xnvme-nvm-vfio.plan
- toolbox/cijoe-pkg-xnvme/testplans/xnvme-zns-vfio.plan
- toolbox/pkgs/alpine-latest.txt
- tools/fio-engine/xnvme_fioe.c
Add a new user-space VFIO-based backend, implemented using libvfn. This backend is largely similar to be:spdk, but the core dependency (libvfn) is, dependency-wise, easier to handle than SPDK.
The backend is feature complete as far as it can be, considering the current limitations of libvfn. This includes no xnvme_buf_realloc() or iovec support. xnvme_buf_vtophys() is also unimplemented (physical address are invalid/irrelevant in this backend).
> New libvfn-based backend

- tests/enum.c
- toolbox/cijoe-pkg-xnvme/testcases/xnvme_tests_enum_any_be_multi.sh
- toolbox/cijoe-pkg-xnvme/testcases/xnvme_tests_enum_any_be_open.sh
- toolbox/cijoe-pkg-xnvme/testcases/xnvme_tests_enum_multi.sh
- toolbox/cijoe-pkg-xnvme/testcases/xnvme_tests_enum_open.sh
- toolbox/cijoe-pkg-xnvme/testsuites/xnvme_admin.suite
- toolbox/cijoe-pkg-xnvme/testsuites/xnvme_admin_idfy_log.suite
- toolbox/cijoe-pkg-xnvme/testsuites/xnvme_admin_no_multi.suite
Make it possible to run `xnvme_tests_enum` with different backends
Closes #129
> tests: add flag for be to enum

- .github/workflows/verify.yml
- include/libxnvme.h
- include/libxnvme_ident.h
- include/libxnvmec.h
- lib/xnvme_be.c
- lib/xnvme_be_spdk_dev.c
- lib/xnvme_ident.c
- lib/xnvmec.c
- toolbox/cijoe-pkg-xnvme/envs/refenv-xnvme.sh
- toolbox/cijoe-pkg-xnvme/hooks/spdk_nvmf_localhost_enter.sh
- toolbox/cijoe-pkg-xnvme/hooks/spdk_nvmf_localhost_exit.sh
- toolbox/cijoe-pkg-xnvme/testcases/fabrics_enum_subnqn.sh
- toolbox/cijoe-pkg-xnvme/testcases/fabrics_info_subnqn.sh
- toolbox/cijoe-pkg-xnvme/testfiles/qemu_setup_nvme_2c3ns_nvm_zrwa.sh
- toolbox/cijoe-pkg-xnvme/testplans/xnvme-fabrics-subnqn.plan
- tools/fio-engine/xnvme_fioe.c
- tools/xnvme.c
Make it possible to specify subnqn when running `xnvme enum` or `xnvme info` using NVMe over Fabrics.
Before this can be merged a test case for this must be added:
> be:spdk: add support for subnqn

- tests/ioworker.c
- toolbox/cijoe-pkg-xnvme/testcases/xnvme_tests_ioworker.sh
- toolbox/cijoe-pkg-xnvme/testcases/xnvme_tests_ioworker_sync.sh
- toolbox/cijoe-pkg-xnvme/testplans/xnvme-base-ramdisk.plan
- toolbox/cijoe-pkg-xnvme/testplans/xnvme-base-spdk.plan
- toolbox/cijoe-pkg-xnvme/testplans/xnvme-base-vfio.plan
- toolbox/cijoe-pkg-xnvme/testsuites/xnvme_ioworker.suite
Add ioworker read write test to relevant backends.
This is in preparation for the ramdisk enhancements, where the ioworker test is likely to be expanded.
> tests: add ioworker test

- include/libxnvmec.h
- lib/xnvme_opts.c
- lib/xnvmec.c
Currently, spdk fails if nsid is not provided.
`--dev-nsid` is optional for `xnvme info`, however if unset it will fail with the userspace driver.
This results in a poor user experience, since the error message is "Input/output error"
closes #131 
(This solution seemed more elegant than making `--dev-nsid` a mandatory argument to `xnvme info`)
This includes #155 and closes #154
> opts: change default nsid to 1

- subprojects/fio.wrap
- subprojects/packagefiles/fio/meson.build
Bumping up fio such that we can compare built-in ``io_uring_cmd`` with xNVMe backend using ``io_uring_cmd``. The built of fio has ``--disable-xnvme`` as from the xNVMe side then the external engine is still in use until we get the Windows issue resolved.
> Update fio subprojects to v3.32

- .github/workflows/verify.yml
- subprojects/packagefiles/spdk/meson.build
- subprojects/packagefiles/spdk/spdk_build.sh
- subprojects/packagefiles/spdk/spdk_configure.sh
- toolbox/pkgs/archlinux-latest.txt
- toolbox/pkgs/centos-centos7.sh
- toolbox/pkgs/centos-centos7.txt
- toolbox/pkgs/centos-stream8.txt
- toolbox/pkgs/centos-stream9.txt
- toolbox/pkgs/debian-bookworm.txt
- toolbox/pkgs/debian-bullseye.txt
- toolbox/pkgs/debian-buster.txt
- toolbox/pkgs/fedora-34.txt
- toolbox/pkgs/fedora-35.txt
- toolbox/pkgs/fedora-36.txt
- toolbox/pkgs/freebsd-13.txt
- toolbox/pkgs/opensuse-leap-15.3.txt
- toolbox/pkgs/opensuse-leap-15.4.txt
- toolbox/pkgs/opensuse-tumbleweed-latest.txt
- toolbox/pkgs/ubuntu-bionic.sh
- toolbox/pkgs/ubuntu-bionic.txt
- toolbox/pkgs/ubuntu-focal.txt
- toolbox/pkgs/ubuntu-jammy.txt
With the next release isa-l will be mandatory in SPDK.
This PR prepares for that by not disabling it in the build and adjusting the pkg-installation scripts in ``toolbox``.
Only the Debian pkg-scripts have been updated at this point, expecting build errors on the other distros.
> 3p:spdk: prep for mandatory isa-l

- include/xnvme_be_linux_libaio.h
- lib/xnvme_be_linux_async_libaio.c
The libaio backend implementation conservatively waits for at least a
single I/O to complete and a timespec to put an upper bound on how long
it waits. Such usage of the Linux aio interface is common as it
conserves CPU utilization.
However, one can trade CPU utilization for reduced latency and increased
IO rate by repeatedly calling io_getevents() with a min-value of 0. This
commit enables such behavior via the "poll_io" option for the libaio
backend implementation.
> be:linux:libaio: add spin-while-waiting

- .github/workflows/verify.yml
- lib/xnvme_be_linux_block.c
- lib/xnvme_be_posix_async_thrpool.c
- tests/lblk.c
- tests/znd_state.c
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/tools/test_xnvme.py
- tools/xdd.c
- tools/xnvme.c
- tools/xnvme_file.c
This is an experiment.
`scan-build` detects errors and warnings that I think is reasonable and should be addressed to improve code quality.
This PR will include fixes for the errors found and based on that we can make a decision of whether to make it a part of our CI.
> CI: add scan-build to workflow

- .github/workflows/verify.yml
- lib/xnvme_buf.c
- tests/lblk.c
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/conftest.py
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/tools/test_xnvme.py
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/xnvme_be_combinations.py
- toolbox/workflow/configs/debian-bullseye.config
- toolbox/workflow/configs/freebsd-13.config
- toolbox/workflow/configs/ramdisk.config
- toolbox/workflow/test-ramdisk.workflow
There is currently no tests of the ramdisk functionality. This adds basic testing of it by:
* Add skip of tests for functionality the ramdisk does not implement
* Add the ramdisk to pytest-parametrization via xnvme_be_combinations
* Add a cijoe-configuration for running tests on local environment using the ramdisk
* Add a workflow running tests using the ramdisk
Additionally, the ``test-ramdisk.workflow`` is executed on Linux Distributions with recent Python and gcc.
This is useful in itself, and additionally a preparation for running full memory-leak checks with ``valgrind`` and other runtime-checkers as this will enable checks of the "upper-half" of xNVMe, that is, the helper-APIs and the backend factory.
This is also done as an enabler for PRs:
* …
> ci,toolbox: add ramdisk testing

- lib/xnvme_be_spdk_dev.c
Signed-off-by: Liad Oz <liadozil@gmail.com>
> be:spdk: process spdk events before reusing controller

- .github/workflows/verify.yml
- Makefile
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/apps/test_fio.py
- toolbox/workflow/provision.workflow
- toolbox/workflow/test-debian-bullseye.workflow
This PR contains a handful of changes to CI and testing which either improves or prepares for further improvement.
Please see the commit-messages for details.
Additional notes are also provided below.
At the time of creating this PR then a testrun consumed about 2 hours of wall-clock time. This is an attempt at cutting that down.
To reduce the time spent, the goal was to make emulated I/O faster. Currently attempted:
* Running qemu with qcow-images on ``tmpfs``
* Running qemu with qcow-images on ``/dev/shm``
Surprisingly, neither of these approaches, although much faster on a local system, does not yield the same benefits when executed via the GitHUB Runner. This might be due to virtualization and/or container-overhead for I/O. The root cause have not been found.
Another approach now, is …
> Misc. ci and testing

- .github/workflows/verify.yml
- Makefile
- python/Makefile
- python/xnvme-core/Makefile
- python/xnvme-cy-bindings/Makefile
- python/xnvme-cy-header/Makefile
Changed the ownership of the build process to a Makefile in python/ instead of xnvme-cy-bindings/Makefile taking control of the other packages.
Improved build-times by avoiding redundant rebuild of build env.
If you want to clean, build or install all of the Python packages, do it from the python/Makefile, and save time by only cleaning when you change the dependencies in the packages.
> mk:py: refactor python makefiles

- Makefile
gen_artifacts didn't correctly call build of all of the Python packages, and would fail to find the xnvme-core and xnvme-header dependencies.
> mk: fix gen_artifacts afte python refactor

- .github/workflows/verify.yml
- Makefile
- python/Makefile
- python/xnvme-core/Makefile
- python/xnvme-cy-bindings/Makefile
- python/xnvme-cy-header/Makefile
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/apps/test_fio.py
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/conftest.py
Before this PR wall-clock was around 1hour and 30min for the debian testrun.
With this PR the wall-clock is down to 40min for the debian testrun.
Trying out:
- result: https://github.com/OpenMPDK/xNVMe/actions/runs/3180754612
- no measurable impact, still at 1hour and 30min
- result: they were already in raw-format, nothing to gain there.
- result: https://github.com/OpenMPDK/xNVMe/actions/runs/3180985899
- result: https://github.com/OpenMPDK/xNVMe/actions/runs/3181649145
- runs out of memory with hugepages... even in combination with reducing fio-work, dropping this pursuit.
- result: https://github.com/OpenMPDK/xNVMe/actions/runs/3182172002
- currently seeing a failure but expecting a reduction to 40 minutes
- yup, after fix, down to 40min for the testrun.
Using ``/dev/shm`` is …
> Reduce CI wall-clock

- python/xnvme-cy-bindings/Makefile
Initially we would only build the Python env on the main entrypoint 'build'. But the CI building the sdist separately and thereby misses the Python env. This is now dynamically built as needed.
> mk: auto-build py env on sdist and bdist

- lib/xnvme_be_linux_async_liburing.c
This PR provides the means to and changes behavior of ``async=io_uring`` and ``async=io_uring_cmd`` in the following ways:
* Share the kernel-side sqpoll thread-pool among multiple ``xnvme_queue`` instances
* Do this by default, disable with env(``XNVME_QUEUE_SQPOLL_AWQ=0``)
* Provides control of cpu affinity for the thread-pool via environment variable ``XNVME_QUEUE_SQPOLL_CPU``
* Ads ``SINGLE_ISSUER`` optimization
> Enable WQ sharing (ATTACH_WQ) for SQPOLL

- .github/workflows/verify.yml
* Work-around to: https://github.com/OpenMPDK/xNVMe/issues/185
* Update of upload/download actions due to:
```Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/upload-artifact```
> ci: Cython workaround and node-related-action-update

- python/xnvme-cy-bindings/xnvme/cython_bindings/tests/test_linux_hugepage.py
We cannot always consistently get a segmented buffer, as there is a bit of chance involved.
If we fail to allocate correctly, we just skip the test. This way, we will optimistically test when the buffer allocates, and otherwise, allow to pass the test without it.
> test,python: test_max_segments_ioctl if allocation fails

- include/libxnvme.h
- include/xnvme_queue.h
- lib/xnvme_be_windows_dev.c
- lib/xnvme_queue.c
- python/xnvme-cy-header/auxiliary/generate_cython_header.py
Now, two things:
* Removes the "SLIST" data structure from the public API
* Adds a missing header-inclusion in the Windows backend
See commit-messages for details.
> Remove SLIST(sys/queue.h) from API

- python/xnvme-cy-bindings/auxiliary/autopxd_py_templates.py
- python/xnvme-cy-bindings/xnvme/cython_bindings/tests/test_basics.py
Fix issue with casting between encapsulated xNVMe objects in Python. Cython wouldn't do the proper casting, and cast a PyObject* instead of the integer value it represents.
> py: fix void_pointer casting

- lib/xnvme_be_fbsd_dev.c
- lib/xnvme_be_linux_dev.c
- lib/xnvme_be_macos_dev.c
- lib/xnvme_be_posix_dev.c
- lib/xnvme_be_spdk_dev.c
- lib/xnvme_be_windows_dev.c
- tests/enum.c
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/logic/test_xnvme_tests_enum.py
Pass a copy of opts, with the respective backend set, to xnvme_dev_open().
This is to avoid a case where a different backend is used for
enumeration and opening the device.
Closes #127
> be: add earmark to dev_open() during enumeration

- docs/contributing/index.rst
- toolbox/pkgs/macos-11.sh
This contains three changes to the contributors section.
1. Provide a check-list of what is expected on behalf of the contributor
2. Explicit mention of DCO, this is preparation for the license-change,
as with it, then the CONTRIBUTING.md will refer to the online
documentation and no longer have a mention of the DCO.
3. Change the "component" prefix convention for example:
-   from: ``be:linux:async:libaio: ...``
-   to: ``be/libaio: ...``
By doing so, the component prefix becomes a lot shorter and the "sub-component" uses "/" instead of ":". Then ":" is used exclusively for the separation of the component from the brief description.
This is done to make the messages shorter and align closer with the commit-style of other projects.
> docs/contributing: add PR checklist, DCO descr. and msg-format-change

- .github/workflows/verify.yml
- build.bat
defined --prefix=/usr during configuration,
changing this so FIO can find xnvme components in
default path.
Signed-off-by: Rishabh Shukla <rishabh.sh@samsung.com>
> be/win: change xnvme installation path to '/usr'

- .github/workflows/verify.yml
The actions use a feature which will be deprecated, thus the CI shows a bunch of deprecation warnings. The latest latest versions 3.1.1 and 3.0.1 have adjusted and updated them should get rid of the deprecation messages.
> ci: update upload/download-artifact actions

- lib/xnvme_be.c
- lib/xnvme_geo.c
- lib/xnvme_lba.c
- lib/xnvme_spec.c
- lib/xnvme_znd.c
- tests/ioworker.c
- tests/scc.c
- tools/fio-engine/xnvme_fioe.c
The format-specificers used for hex-values e.g. lx/llx does not match the on Mac/clang. This changes the the use of those format-specifiers to use the PRIx64/PRIu64/PRIx16 macros.
> Change format-specifiers to PRI-macro

- toolbox/xnvme-driver.sh
xnvme-driver fails on FreeBSD in the CI, this is because FreeBSD is using bash 2.5.3. Which has deprecated the use of parentheses around brackets. Every instance of `([0-9])` has been changed to `[0-9]`
> toolbox/xnvme-driver: adapt syntax to bash 2.5.3

- python/xnvme-cy-bindings/auxiliary/autopxd_py.py
autopxd2 v2.3.0 added support for `const` qualifiers. These caused the auto-generation of the `.pyx` files to fail. This has been resolved now.
Unfortunately, this does not resolve any of the `[-Wdiscarded-qualifiers]` warnings.
Currently the only `const` qualifiers that end up in the `.pyx` files are `const char *`, this is because python/cython complains if I put them in front of pyObjects, i.e. `xnvme_void_p`. 
Unless we can find a way to do that, perhaps it is better to just discard the const qualifiers instead, to keep the complexity of `autopxd_py.py` down.
@Baekalfen @safl can I get your opinion on this?
> py/cython-bindings: handle const qualifiers in function signatures

- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/tools/test_xnvme.py
The test is trying to set a Temperature Threshold, which is a non-saveable feature. As such, it should not try to save it.
The only reason this is not failing currently is because the `xnvme` cli is hardcoded to never save. However, #221 changes this to be implemented correctly and then the test fails.
> ci,toolbox/cijoe: Don't try to save non-saveable feat

- .github/workflows/verify.yml
Temporary work-around to: https://github.com/OpenMPDK/xNVMe/issues/252
> gha/build: skip Debian Bookworm build and ramdisk tests

- meson.build
- subprojects/packagefiles/fio/meson.build
- tools/fio-engine/meson.build
adding fix to remove the meson 'sandbox voilation' warning due to direct access of subprojects headers files inside the xNVMe main meson.build file.
> meson:build:win: fix meson 'sandbox violation' warning

- meson.build
Currently this check is run regardless of the system, however on some systems the command either fails or doesn't exist. This can cause the build to fail.
Instead this should only be run if the system is linux.
> meson: only check for CentOS 7 if sys == "linux"

- rust/.gitignore
- rust/README.rst
- rust/xnvme-sys/Cargo.toml
- rust/xnvme-sys/src/main.rs
- rust/xnvme/Cargo.toml
- rust/xnvme/src/main.rs
This is what is used when name-squatting xNVMe on crates.io:
- https://crates.io/crates/xnvme-sys
- https://crates.io/crates/xnvme
> rust: add a skeleton for xNVMe crates

- include/libxnvme_pp.h
- include/libxnvmec.h
- lib/xnvmec.c
- python/xnvme-cy-bindings/auxiliary/autopxd_py.py
- tests/enum.c
- tools/lblk.c
- tools/xnvme.c
- tools/zoned.c
xnvme_enumeration belongs to libxnvmec, thus it has the wrong prefix. This commit corrects this prefix.
> xnvmec: rename xnvme_enumeration* to xnvmec_enumeration*

- lib/xnvme_be_linux_async_ucmd.c
Liburing uses nolibc by default in some architecture. This means that it might have its own version of free. Use the liburing free version for the uring probe so we do not run into incompatibilities
> be/linux: Use io_uring_free_probe instead of free

- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/logic/test_xnvme_tests_kvs.py
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/worklets/guest_start_nvme.py
- toolbox/workflow/configs/debian-bullseye.config
@ankit-sam this should be what is needed for the ``build-and-test`` to have an NVMe-namespace with FDP enabled to use for testing. When writing this, I realize a short-coming/todo:
> Add KV and FDP enabled namespaces

- include/libxnvme_adm.h
- include/libxnvme_nvm.h
- include/libxnvme_spec.h
- include/libxnvmec.h
- lib/xnvme_adm.c
- lib/xnvme_nvm.c
- lib/xnvme_spec.c
- lib/xnvme_spec_pp.c
- lib/xnvmec.c
- python/xnvme-cy-bindings/auxiliary/autopxd_py.py
- python/xnvme-cy-header/auxiliary/generate_cython_header.py
- toolbox/cijoe-pkg-xnvme/src/cijoe/xnvme/tests/tools/test_fdp.py
- tools/xnvme.c
This series adds FDP support in xNVMe.
The initial 2 commits modify the log pages and set / get feature commands by adding a prep function. This is done to avoid changes to the existing api so that it does not become too bulky.
The next 4 commit introduces the required changes in spec, tools, cli and api.
This series is missing changes to toolbox (test) which I will update once Qemu changes are upstream
> Add FDP changes in xNVMe

- .github/workflows/verify.yml
When switching runners from one to six per host, then the left-over
state of qemu-guests collides.
This change prevents this by first killing qemu and then removing
$HOME/guests before provisioning+starting the qemu-guest.
Thereby ensuring that no previous qemu instance is running and no
auxilary files are left over.
> ci/build_and_test: kill qemu and remove guest-directory 

- .github/workflows/verify.yml
- Makefile
- lib/meson.build
- meson.build
- python/xnvme-core/requirements.txt
- python/xnvme-core/xnvme/ctypes_bindings/library_loader.py
- python/xnvme-cy-bindings/setup.py
- python/xnvme-cy-header/xnvme/cython_header/tests/setup.py
- subprojects/packagefiles/spdk/meson.build
- subprojects/spdk.wrap
- toolbox/pkgs/centos-stream9-build.sh
- toolbox/pkgs/fedora-36-build.sh
- toolbox/pkgs/fedora-37-build.sh
- toolbox/pkgs/fedora-38-build.sh
A refactoring of the build system for xNVMe is required to get closer to the goal of distributing xNVMe in the native package system of linux distros, like Fedora and Debian.
The main goal is to move away from bundling libraries into xNVMe by default. Instead, xNVMe should produce a "clean" library by default and only allow for bundling when building from source.
A consequence of this is that SPDK will only be available when using the bundled library built from source.
> Refactor build of xNVMe

- xnvme.spec.in
when directory is created in some other package it occur below error file /usr/local/lib64/pkgconfig from install of xnvme-0.6.0-0.x86_64 conflicts
Add executable permission for library, bin files
> rpmbuild: fix directory conflicts error

- include/libxnvme.h
- lib/xnvme_be_spdk_dev.c
- lib/xnvme_opts.c
We have found that for certain applications, we would want to change/remove the timeout on admin commands and io commands. This commit allows to choose the command timeout from the xnvme_opts
> be:spdk: Add option to control admin and io command timeout

- cijoe/tests/conftest.py
By applying a CPU mask to the SPDK NVMe-oF target we can massively speed up the fabrics tests.
Additionally, we no longer need to adjust the parameters of the transport, and they can remain in the default configuration.
> fix(cijoe/tests): Speed up fabrics tests

- lib/xnvme_be_vfio_async.c
- lib/xnvme_be_vfio_mem.c
- lib/xnvme_be_vfio_sync.c
- meson.build
- toolbox/pkgs/archlinux-latest.sh
- toolbox/pkgs/centos-centos7.sh
- toolbox/pkgs/centos-stream8.sh
- toolbox/pkgs/centos-stream9.sh
- toolbox/pkgs/debian-bookworm.sh
- toolbox/pkgs/debian-bullseye.sh
- toolbox/pkgs/debian-buster.sh
- toolbox/pkgs/emitter/templates/src-libvfn-centos-centos7.sh.jinja
- toolbox/pkgs/emitter/templates/src-libvfn.sh.jinja
- toolbox/pkgs/fedora-36.sh
- toolbox/pkgs/fedora-37.sh
- toolbox/pkgs/fedora-38.sh
- toolbox/pkgs/gentoo-latest.sh
- toolbox/pkgs/opensuse-leap-15.3.sh
- toolbox/pkgs/opensuse-leap-15.4.sh
- toolbox/pkgs/opensuse-tumbleweed-latest.sh
- toolbox/pkgs/ubuntu-focal.sh
- toolbox/pkgs/ubuntu-jammy.sh
- toolbox/pkgs/ubuntu-kinetic.sh
Update the libvfn-based backend to libvfn v2.0.0.
> be/vfio: bump libvfn to v2.0.0

- lib/xnvme_be_spdk_dev.c
When compiled without debug-mode, unused parameter warnings are observed for spdk spdk backend. Add a fix for that.
[84/201] Compiling C object lib/libxnvme.so.p/xnvme_be_spdk_dev.c.o ../lib/xnvme_be_spdk_dev.c: In function ‘timeout_cb_func’: ../lib/xnvme_be_spdk_dev.c:428:41: warning: unused parameter ‘qpair’ [-Wunused-parameter]
428 |                 struct spdk_nvme_qpair *qpair, uint16_t cid)
|                 ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
../lib/xnvme_be_spdk_dev.c:428:57: warning: unused parameter ‘cid’ [-Wunused-parameter]
428 |                 struct spdk_nvme_qpair *qpair, uint16_t cid)
Fixes - c8dfb1964d54181e2b2e07eb4da7434c4a5d4863
> fix compilation warning for unused parameters

- python/bindings/auxiliary/patch_ctypes_bindings.py
- python/bindings/xnvme/ctypes_bindings/library_loader.py
**Use-case**
My system might differ from yours, I may not have pkg-config, or I may have a copy of xNVMe installed elsewhere.
This change permits me to override the library-loading logic by exporting `XNVME_LIBRARY_PATH`, pointing to the library file I want to load.
This change even allows users of any downstream applications to work around issues of locating the xNVMe library on their systems, without the application making special provisions.
> allow overriding library loading by env var

- .github/workflows/verify.yml
With these changes, then it should possible to enable the github merge-queue. This means that:
* When a PR for the ``next`` branch meets all requirements
* Is rebased / up-to-date
* Has been reviewed
* Passes "fast" checks (code-format and build-checks)
Then it can go into the "merge-queue", when entering the merge-queue, additional longer-running checks are performed, specifically: spinning up a virtual machine (qemu) with NVMe device emulation and running the full functional test-suite on it. In case the testing passes, then the PR is "automatically" merged into ``next``. In case it fails, then it is removed from the merge-queue and the submitter can choose to:
* Reproduce the issue locally
* Make changes
* Send to the merge-queue again
The merge-queue is introduced to make it more …
> fix(gha): adjust conditions for build-and-test

- python/bindings/xnvme/ctypes_bindings/library_loader.py
`subprocess.run` raises FileNotFoundError iff. binary (pkg-config) is not in PATH.
Catch this error, same as if pkg-config returned a non-zero exit code.
> catch exc iff pkg-config is not in path

- python/bindings/auxiliary/patch_ctypes_bindings.py
This is a cosmetic change.
Use `textwrap.dedent` to automatically dedent a block of text such that all leading whitespace occurring for each non-empty line is removed. This permits using appropriately indented multi-line strings.
Beware: The wording in the "guard" close is changed to assume the merger of
https://github.com/OpenMPDK/xNVMe/pull/308
> fix(py/bindings): use textwrap.dedent for snippets

- cijoe/tests/logic/test_xnvme_tests_kvs.py
- tests/kvs.c
There were two oversights in the kvs test, these have been corrected.
Additionally, a cijoe test has been added using the functionality that previously failed.
This should resolve #310
> Fix KVS test

- docs/autogen/Makefile
- docs/autogen/requirements.txt
- docs/getting_started/index.rst
- include/libxnvme_kvs.h
- include/libxnvme_mem.h
- include/libxnvme_spec.h
This fixes the current breakage of the documentation generation. It fails as there are now ``.cmd`` files for Windows, however, it is not running in a Windows environment, thus need to be generated seperately and thus skipped for now in the automated doc. generator.
> Fix breakage of the automated doc. generator

- toolbox/pkgs/fedora-36.sh
- toolbox/pkgs/fedora-37.sh
- toolbox/pkgs/fedora-38.sh
The `test_linkandload` fails on fedora since zlib-devel is missing. 
With this addition, that is no longer the case.
> fix(build/fedora): add zlib-devel dependency

- lib/xnvme_be_macos_admin.c
- lib/xnvme_be_macos_dev.c
Compilation fails without this include
> be:macos: add missing include of mach_error.h

- meson.build
The license of xNVMe was previously changed from APACHE to BSD-3-Clause, however, the meson.build was missing this change. Thus changing it here.
> fix(meson): change license to 'BSD-3-Clause'

- cijoe/workflows/docgen.yaml
Previously, then 'cijoe-pkg-qemu' provided a script to start qemu with a
complicated NVMe-device configuration. This, has later been removed from
'cijoe-pkg-qemu' as it goes well beyond the scope of the package.
Instead, 'xnvme_guest_start_nvme' extends the 'cijoe-pkg-qemu'
capabilities, and does the advanced config. By doing so, then the script
comes closer to where it is used. That is, it is usually the xNVMe
project that changes this file, thus it makes sense that it lives inside
the xNVMe repository.
Note, 'cijoe-pkg-qemu', still has scripts for startin/stopping qemu with
different configurations, it is just a matter of moving the config
specific to xNVMe into the xNVMe repository.
> fix(cijoe): change the script that starts qemu

- .github/workflows/verify.yml
While attemptning to fix the docgen build-issue, then github had an outage / breakage of the checkout action. On:
https://github.com/actions/checkout/issues/1448
Then it is reported that the current fix is to bump to v4.0.0, thus, trying it out here.
> fix(gha): bump checkout to v4.0.0

- include/xnvme_be_vfio.h
- lib/xnvme_be_vfio_sync.c
The VFIO/libvfn interface used a deprecated member 'cqe_sync' on the state struct. This is changed to the correct command context, so the completion result is returned.
Unused members 'queue_id' and 'cqe_sync' removed from VFIO state.
> vfio: fix completion result for sync io

- Makefile
The mk-config-helper-targets for various features were previously somewhat convenient as examples of disabling features requiring third-party libraries which were **always** fetched via meson-subprojects. Also, as a means to disable when a dependency did not function properly in a given environment.
Now that the build instead links with the dependencies when available on the system. Then, third-party dependencies simply disabled when not available. Thus, those targets are no longer needed.
The exception to this is SPDK, thus, the 'config-slim' serves as an example of disabling the SPDK subproject, and disabling other dependencies even when they are found on the system.
> fix(mk): remove deprecated helper-targets and adjust config-slim

- subprojects/packagefiles/spdk/meson.build
- subprojects/packagefiles/spdk/spdk_configure_debug.sh
If xNVMe is built with buildtype=debug, configure SPDK to use debug too.
I believe this is useful for debugging
> feat(build/spdk): use debug for SPDK if enabled for xNVMe

- subprojects/packagefiles/spdk/meson.build
- subprojects/packagefiles/spdk/patches/spdk-0001-nvmf-add-passthru-handlers-for-IOCS-specific-identif.patch
- subprojects/packagefiles/spdk/patches/spdk-0002-nvmf-Added-passthru-support-for-log-zone-changes.patch
- subprojects/packagefiles/spdk/spdk_configure.sh
- subprojects/packagefiles/spdk/spdk_configure_debug.sh
- subprojects/spdk.wrap
- toolbox/pkgs/alpine-latest.sh
- toolbox/pkgs/archlinux-latest.sh
- toolbox/pkgs/centos-stream9.sh
- toolbox/pkgs/debian-bookworm.sh
- toolbox/pkgs/debian-bullseye.sh
- toolbox/pkgs/debian-trixie.sh
- toolbox/pkgs/emitter/deps.yaml
- toolbox/pkgs/fedora-36.sh
- toolbox/pkgs/fedora-37.sh
- toolbox/pkgs/fedora-38.sh
- toolbox/pkgs/gentoo-latest.sh
- toolbox/pkgs/opensuse-tumbleweed-latest.sh
- toolbox/pkgs/oraclelinux-9.sh
- toolbox/pkgs/rockylinux-9.2.sh
- toolbox/pkgs/ubuntu-focal.sh
- toolbox/pkgs/ubuntu-jammy.sh
- toolbox/pkgs/ubuntu-lunar.sh
Bump SPDK since #350 uses a patch that is available in SPDK v23.01.
This requires a new dependency 'libarchive' for the version of DPDK which comes
with SPDK v23.01.
Besides this, the `spdk_configure.sh` script has been updated to disable
more things we don't need.
> feat(build/spdk): bump to v23.01

- lib/xnvme_be_linux_async_liburing.c
Instead of requiring `XNVME_QUEUE_BATCHING = 1` to enable batching, now we require `XNVME_QUEUE_BATCHING_OFF = 1` to disable batching
> feat(be/liburing): turn on batching by default

- docs/tutorial/index.rst
Without this, then the fdp-tutorial is not available.
> fix(docs): add fdp-tutorial to index

- toolbox/pkgs/alpine-latest.sh
- toolbox/pkgs/archlinux-latest.sh
- toolbox/pkgs/centos-stream9.sh
- toolbox/pkgs/debian-bookworm.sh
- toolbox/pkgs/debian-bullseye.sh
- toolbox/pkgs/debian-trixie.sh
- toolbox/pkgs/emitter/templates/src-libvfn.sh.jinja
- toolbox/pkgs/fedora-36.sh
- toolbox/pkgs/fedora-37.sh
- toolbox/pkgs/fedora-38.sh
- toolbox/pkgs/gentoo-latest.sh
- toolbox/pkgs/opensuse-tumbleweed-latest.sh
- toolbox/pkgs/oraclelinux-9.sh
- toolbox/pkgs/rockylinux-9.2.sh
- toolbox/pkgs/ubuntu-focal.sh
- toolbox/pkgs/ubuntu-jammy.sh
- toolbox/pkgs/ubuntu-lunar.sh
Currently we are building libvfn with debug enabled, this leads to unwanted debug messages getting printed in our CI. Silence these by building as release.
This closes #324
> fix(toolbox/pkgs): build libvfn as release

- cijoe/tests/logic/test_xnvme_tests_ioworker.py
- cijoe/tests/xnvme_be_combinations.py
- cijoe/workflows/test-debian-bullseye.yaml
- lib/xnvme_be_vfio_async.c
- lib/xnvme_be_vfio_mem.c
- lib/xnvme_be_vfio_sync.c
- python/tests/xnvme_be_combinations.py
This turned out to uncover a handful of issues:
The two latter items are captured in issues.
> fix(cijoe,python): add 'vfio' to backend-test-matrix

- lib/xnvme_be.c
- lib/xnvme_be_linux_dev.c
A long-standing thing to address is: https://github.com/OpenMPDK/xNVMe/issues/230
This is an initial improvement in this area, motivated by PR https://github.com/OpenMPDK/xNVMe/pull/365
However, instead of going with PR #365 then a bit more work is done here to enable the correct internal representation of the device-type.
> NVMe Controller handles (``/dev/nvme0``) in Linux backend

- docs/contributing/release-checklist.rst
This briefly describes how to publish the Python xNVMe bindings package to the Python package index and how to published the Rust crate to crates.io.
> docs(release-checklist): add description on Python + Rust publication

- rust/xnvme-sys/build.rs
The path to the xNVMe library header was hardcoded. By doing so, 'cargo
build' would generate bindings. However, the build would fail when
invoked via 'cargo publish' as the hardcoded path would be incorrect.
Thus, instead of generating the bindings based on the relative path, the
bindings are generated based on the header found via
system_deps/include_paths. That is, against the library header, the
Rust-crate "system_deps" has verified that it is available in the
correct version.
> fix(rust): use header found via system_deps()

- cijoe/configs/debian-bullseye.toml
- cijoe/tests/tools/test_xnvme.py
- lib/xnvme_be_linux_nvme.c
- lib/xnvme_be_spdk_admin.c
- tools/xnvme.c
Pseudo commands (ctrl reset, ns rescan and subsystem reset) support in xNVMe.
1. Adding ctrl reset, ns rescan and subsystem reset.
2. Add pseudo commands testing tool.
> Pseudo commands support

- cijoe/tests/tools/test_xnvme.py
- include/libxnvme.h
- include/libxnvme_spec_pp.h
- include/libxnvme_topology.h
- lib/xnvme_be_linux_nvme.c
- lib/xnvme_be_spdk_admin.c
- lib/xnvme_spec_pp.c
- lib/xnvme_topology.c
- subprojects/packagefiles/spdk-win/patches/spdk-win-0003-lib-nvme-restore-spdk_nvme_ctrlr_get_registers.patch
- tools/xnvme.c
This is a refactoring of PR https://github.com/OpenMPDK/xNVMe/pull/350 after the introduction of the following preparation work:
* https://github.com/OpenMPDK/xNVMe/pull/322
* This provides a general interface for things like resets/rescans, such that the backend interface does not need to change when new functionality is needed
* https://github.com/OpenMPDK/xNVMe/pull/353
* This provides initial implementations of the interface in the Linux and SPDK backends
* https://github.com/OpenMPDK/xNVMe/pull/372
* With this, we get the register-mapping capabilities from SPDK, instead of backporting patches
* https://github.com/OpenMPDK/xNVMe/pull/385
* Without this, it was not possible to get a handle to e.g. ``/dev/nvme0`` to do the various resets
Last, a commit is added invoking show-regs via …
> get/show controller-registers using backends: [linux,spdk]

- cijoe/configs/debian-bullseye.toml
- subprojects/packagefiles/spdk/patches/spdk-0005-lib-bdev-Add-spdk_bdev_is_kv-to-bdev-interface.patch
- subprojects/packagefiles/spdk/patches/spdk-0006-nvmf-Support-adding-KV-NS-to-nvmf_tgt.patch
- subprojects/packagefiles/spdk/patches/spdk-0007-lib-nvmf-Add-I-O-cmd-passthru-for-KV.patch
- subprojects/packagefiles/spdk/patches/spdk-0008-lib-nvmf-Add-identify_-_iocs-passthru-for-KV.patch
These additions allow for the creation of KV namespaces in the `nvmf_tgt` app, and the submission of KV cmds over nvmf.
To be clear, all of these patches only affect the SPDK `nvmf_tgt` app, and not the xNVMe SPDK backend.
> feat(be/spdk): enable KV over nvmf

- rust/xnvme-sys/build.rs
The search in include-headers did not break when the header was found, thus, it would only setup header_path correctly when it was located in the last iterated include_path.
> fix(rust): add loop-breakout when header is found

- lib/xnvme_be_linux_async_ucmd.c
These checks trigger I/O fail when metadata is enabled.
> Remove metadata buffer checks

- include/libxnvme_nvm.h
- lib/xnvme_nvm.c
According to the spec there is no such thing as sdlba for write zeroes, this is only used for copy
> fix(nvm): change sdlba to slba for write_zeroes

- cijoe/workflows/test-debian-bullseye.yaml
Previously, this was disabled because the performance of nvme/tcp was very slow - this has now been fixed, thus enabling the tests.
> feat(cijoe/tests): test ioworker on fabrics

- lib/xnvme_queue.c
The callback on the command-context initilization is set to NULL. When set to NULL, then it is the backend responsibility to check whether a valid function pointer is set upon "callback-time".
To avoid having to check this, then this change assigns a default NOOP callback.
> feat(queue): add a default NOOP callback

- cijoe/configs/debian-bookworm-arm.toml
- cijoe/configs/debian-bullseye.toml
The remote was pointing to a non-existant repository. This fixes it by pointing it to https://github.com/torvalds/linux.git
> fix(cijoe/configs): correct the linux.repository.remote

- Makefile
For producing documentation, with output from command-examples included,
then different resources are needed such as a virtual machine with the
proper device configuration, and wall-clock time to execute all the
commands. A helper 'cijoe-do-docgen' takes care of this.
However, when reducing the scope to rendering the prose of the
documentation, then the build requirements is reduced to the setup of
a Python venv. and executing doxygen, breathe, a couple of scripts,
and sphinx-doc.
Such rendering is done by executing 'make' inside of 'docs/autogen', for
convenience, then this is lifted up into the Makefile in the root of the
repository. Such that 'make docs' will to a quick rendering, providing a
significantly simpler means to maintain and expand documentation.
> feat(mk): add helper producing documentation

- cijoe/tests/logic/test_xnvme_tests_copy.py
- include/libxnvme_cli.h
- lib/xnvme_cli.c
- tests/copy.c
Previously, we sent 128 Source Ranges even though we only filled out the
first. This PR fixes this.
Furthermore, the MSSRL is now used to limit the number of bytes per
Source Range.
> fix(tests/copy): send correct amount of Source Range entries

- toolbox/pkgs/emitter/deps.yaml
- toolbox/pkgs/gentoo-latest.sh
Seems the emerge package has been renamed.
The new one is here:
https://packages.gentoo.org/packages/dev-build/meson
> fix(pkgs/gentoo): rename dev-util/meson to dev-build/meson

- lib/xnvme_be_spdk_dev.c
During xnvme enumeration for spdk backend trtype is not set for TCP, RDMA, FC and CUSTOM transport. If assertions are enabled in spdk, this leads to `spdk_nvme_trid_populate_transport()` throw below specified error.
`DBG:xnvme_be_spdk_dev.c:xnvme_be_spdk_enumerate-687: INFO: trtype: TCP, # 2 of 4 DBG:xnvme_be_spdk_dev.c:_xnvme_be_spdk_ident_to_trid-300: FAILED: uri: , trtype: TCP DBG:xnvme_be_spdk_dev.c:xnvme_be_spdk_enumerate-693: SKIP: !_xnvme_be_spdk_ident_to_trid() nvme.c:1035:spdk_nvme_trid_populate_transport: *ERROR*: no available transports xnvme: nvme.c:1036: spdk_nvme_trid_populate_transport: Assertion `0' failed. Aborted (core dumped)`
Set trtype to avoid assertion 0 failed error.
> fix assertion failure with xnvme enum

- include/libxnvme_spec.h
- lib/xnvme_be_ramdisk_admin.c
- lib/xnvme_dev.c
- lib/xnvme_spec.c
- python/tests/test_lblk.py
- tests/scc.c
- tools/xnvme.c
I have cleaned up the identification part of the documentation, such that it is more clear which idfy structs are command set specific and which aren't.
There were multiple duplicated structs these have been cleaned up.
> Refactor identification

- lib/xnvme_spec.c
Output reclaim unit handle status descriptors to either the requested limit or the device supported value, whichever is smaller.
> fix reclaim unit handle status output format

- lib/xnvme_cli.c
When `opt_type == XNVME_CLI_LFLG`, `arg` will always be 0x0, so checking for this variable was redundant. This fix only removes the check for `arg` for `xnvme_cli_opt` values that are used as the `XNVME_CLI_LOPT` type.
This solves #272.
> fix(xnvme/cli): handle LFLG type arguments in xnvme_cli_assign_arg

- tests/map.c
clang-format-14 (CI) and clang-format-18 (local) seems to only disagree
about this macro. To avoid the error write out the macro.
I also believe that the written out macro is more readable.
> fix(tests/map): write out macro

- tools/xnvme.c
Including the nsid if it is not needed, eg. cns=1 (idfy-ctrlr), can in some cases cause the command to fail.
Closes: #465
> fix(tools/xnvme/idfy): only add nsid if needed

- include/libxnvme_opts.h
- lib/xnvme_be_spdk_dev.c
Relates to #462
This only adds the option to specify keep alive timeout, if this option is used, the user must send the KEEP_ALIVE command on their own.
> feat(spdk): add keep_alive_timeout to opts

- docs/autogen/dest.py
The theme introduced in https://github.com/xnvme/xnvme/pull/430 combines the website and the sphinx-doc emitted generation into a single site. Thus, to manage this, then the deployment script needs to handle organizing not just ``docs/<branch>/<tag>`` but also the root of the GItHub pages repository / website.
> Adjust website / docs. deployment script to the new theme

- .github/workflows/verify.yml
- examples/meson.build
- lib/libxnvme.map
- lib/meson.build
- tests/enum.c
- tests/meson.build
- tools/meson.build
This adds control over our exported symbols and leverages meson functionality to control whether a user wants both the static and shared libraries or just one of them.
> Revisit how we handle the shared library in Meson

- .github/workflows/verify.yml
- docs/autogen/conf.py
- docs/autogen/dest.py
- docs/contributing/contributing-branches.rst
* Add an option to dest.py to select which instance of the website / documentation to add to the site-root and set as "current" in versions.json
- Previously, this would always be 'main', however, this implies that the website can only be updated with releases of xNVMe, this is not practical. Thus this to provide pushes to e.g. the 'website' branch to update the site-root.
- Care should be taken to then have such a 'docs' branch be based on top of 'main' such that changes in e.g. api or otherwise does not trickle into the docs.
* Extend the autogen/dest.py script to emit versions.json for the PyData theme to consume
* Adjust conf.py; set html-theme options for the PyData config to consume the generated versions.json
> Documentation overhaul: add user-selectable versions and current site

- .github/workflows/verify.yml
- docs/autogen/Makefile
- docs/autogen/conf.py
- docs/autogen/dest.py
- docs/autogen/test_multi_version.sh
- docs/contributing/contributing-branches.rst
- docs/contributing/release-checklist.rst
* Drop the ``--current`` argument to dest.py, the current / preferred version is now always the latest version
* The version of xNVMe is added to the theme options ``html_theme_options.switcher.version_match`` to enable correct behavior or the multi-version switcher
* Added visual indicators when looking at an old version and inform when looking at the development version via the ``html_theme_options.show_version_warning_banner``
* Update the documentation describing what the branch named **docs** is for, this was previously the task of **current**
* Since the purpose of the branch is to host changes to the website for the most recent release, then i find ``docs`` to be a better suited name
**NOTE**: This is currently failing due to unrelated failure of HW for benchmarking
> documentation overhaul: version selection with visual indicators

- .github/workflows/verify.yml
- Makefile
- cijoe/configs/bench-amd.toml
- cijoe/configs/bench-intel.toml
- cijoe/configs/debian-bookworm-arm.toml
- cijoe/configs/debian-bullseye.toml
- cijoe/configs/freebsd-13.toml
- cijoe/configs/perf-lat-freebsd.toml
- cijoe/configs/perf-lat-linux.toml
- cijoe/scripts/git_sync.py
- cijoe/scripts/xnvme_bindings_py_install_tgz.py
- cijoe/workflows/test-debian-bullseye.yaml
- cijoe/workflows/test-freebsd-13.yaml
In cijoe v0.9.32, the key `transport` has been moved under `cijoe`. Additionally, packages for qemu, linux and fio are included in the main package and no longer needs to be injected when installed.
> fix(cijoe/version): bump to v0.9.34

- lib/xnvme_dev.c
Add a check for 'dev_uri' in xnvme_dev_open() to prevent segmentation
faults.
This defensive check helps avoid potential crashes when 'dev_uri' is
not specified, such as when calling xnvme_dev_open(argv[1], ...) without
providing an argument. Arguably, improving the initial experience for
new users by ensuring a valid argument is provided.
> feat(dev): add check of 'dev_uri' in xnvme_dev_open()

- toolbox/pkgs/emitter/deps.yaml
- toolbox/pkgs/freebsd-13.sh
Currently, the FreeBSD build fails because it tries to install pipx using the wrong pkg-name. This fixes the issue
> Fix FreeBSD build errors

- cijoe/scripts/spdk_build_modded.py
- cijoe/scripts/spdk_build_modded_freebsd.py
After we changed the latency workflows to use upstream SPDK at tag v24.05, we cannot do `git pull --rebase`, as we are not in a branch. The `repository_prep` script makes sure that the repository is up to date with the tag, so the command is redundant and can be removed without problems.
> fix(cijoe/latency): remove redundant git pull command

- cijoe/scripts/fio_latency.py
Some of the parameters were unnecessary and some were wrong. See issue #371
> fix(cijoe/latency): remove wrong fio parameters

- cijoe/scripts/bdevperf.py
- cijoe/scripts/bench_plotter.py
- cijoe/scripts/benchmark_normalize.py
- cijoe/templates/perf_report/bench.jinja2.rst
- cijoe/templates/perf_report/style.yaml
Add graphs for CPU usage (in percent) to the "xNVMe in SPDK" report.
Let's talk about how they should be visualized:
[xnvme-in-spdk.pdf](https://github.com/user-attachments/files/16507554/xnvme-in-spdk.pdf)
Memory utilization has been dropped. 
I could use some feedback on the Methodology section I've added.
> feat(cijoe/bench): add resource utilization plots to report

- .github/workflows/verify.yml
- cijoe/auxiliary/plot-latency-legends.yaml
- cijoe/configs/perf-lat-windows.toml
- cijoe/scripts/fio_latency.py
- cijoe/scripts/fio_prep.py
- cijoe/scripts/fio_prep_windows.py
- cijoe/scripts/latency_plotter.py
- cijoe/scripts/sysinfo_report.py
- cijoe/scripts/xnvme_build.py
- cijoe/scripts/xnvme_install.py
- cijoe/workflows/benchmark-provisioning-windows.yaml
- lib/xnvme_be_windows.c
Run latency benchmarking on Windows, comparing the three backends `ioring`, `iocp` and `iocp_th` from the xNVMe engine to the fio engine `windowsaio`.
[latency-windows.pdf](https://github.com/user-attachments/files/16611980/latency-windows.pdf)
> Run latency benchmarking on Windows
